//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidad
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Empleados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleados()
        {
            this.Licencias = new HashSet<Licencias>();
            this.Permisos = new HashSet<Permisos>();
            this.Salidas = new HashSet<Salidas>();
            this.Vacaciones = new HashSet<Vacaciones>();
        }
    
        public int Id { get; set; }
        public string Codigo { get; set; }
        [Required(ErrorMessage = "No puede dejar el campo nombre vacio !")]
        public string Nombre { get; set; }

        [Required(ErrorMessage = "No puede dejar el campo apellido vacio !")]
        public string Apellido { get; set; }
        [Required(ErrorMessage = "No puede dejar el campo telefono vacio !")]
        public string Telefono { get; set; }
        [Required(ErrorMessage = "Debe seleccionar un departamento !")]
        public Nullable<int> Departamento_Id { get; set; }
        [Required(ErrorMessage = "Debe seleccionar un cargo !")]
        public Nullable<int> Cargo_Id { get; set; }
        public Nullable<System.DateTime> Fecha_Ingreso { get; set; }
        [Required(ErrorMessage = "No puede dejar el campo salario vacio !")]
        public Nullable<decimal> Salario { get; set; }
        public string Estatus { get; set; }
        public string Retrato { get; set; }
        public string Sexo { get; set; }
            
        public virtual Cargos Cargos { get; set; }
        public virtual Departamentos Departamentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Licencias> Licencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Permisos> Permisos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Salidas> Salidas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vacaciones> Vacaciones { get; set; }
    }
}
