//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidad
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Vacaciones
    {
        public int Id { get; set; }
        public int Id_Empleado { get; set; }
        [Required(ErrorMessage = "Debe elegir la fecha desde !")]
        public Nullable<System.DateTime> Desde { get; set; }
        [Required(ErrorMessage = "Debe elegir la fecha hasta !")]
        public Nullable<System.DateTime> Hasta { get; set; }
        public Nullable<int> Año_Correspondiente { get; set; }
        public string Comentarios { get; set; }
    
        public virtual Empleados Empleados { get; set; }
    }
}
